### ISSUE TITLE
Unidad 2 Mapa Mental 

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Daniel-Velasco-Lopez#1]
Daniel Velasco López
Unidad 2 Mapa Mental 

![mapa unidad 2](https://user-images.githubusercontent.com/112217987/191601850-4df61c61-647a-4a92-aa1d-e3e43380e335.png)

**Comment by YaelTrinidad** [comment]
ACT 4 MAPA MENTAL
"TIPOS DE COMUNICACIÒN"
DEL 20% DE LA ACTIVIDAD, DADA LA RUBRICA OBTUVISTE EL 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
